### ISSUE TITLE
Unhandled exception when a directory is given in place of the filename

### ISSUE THREAD

**Issue by anson-vandoren** [aaronwhittier/cribl#13]
On my test machine:

```
$ ls -la /var/log
drwxr-xr-x     - root  2 Mar 02:10 atop
drwx------     - root 21 Apr 03:34 audit
.rw-rw----  2.7k root 26 Sep 02:02 btmp
drwxr-sr-x@    - root 25 Aug 06:42 journal
.rw-rw-r--  292k root 26 Sep 02:02 lastlog
drwxr-xr-x     - root 26 Aug 06:40 libvirt
drwxr-xr-x     - root  6 Dec  2021 old
.rw-r--r--  177k root 19 Sep 15:11 pacman.log
drwx------     - root 26 Sep 15:21 private
drwxr-xr-x     - root 26 Aug 06:40 swtpm
.rw-r--r--  1.9G root 26 Sep 14:39 testlog.log
.rw-rw-r--   56k root 26 Sep 02:02 wtmp
$ curl "localhost:8080/LogEntries?filename=swtpm"
HTTP/1.1 500 Internal Server Error
Content-Length: 0
Date: Mon, 26 Sep 2022 22:26:53 GMT
Server: Kestrel
```

On the service logs:

```
2022-09-26 22:27:18.9418| INFO|          LogEntriesController|Getting all lines from file swtpm
2022-09-26 22:27:18.9422|ERROR|                       Kestrel|Connection id "0HML01KBOFHH7", Request id "0HML01KBOFHH7:00000002": An unhandled exception was thrown by the application. System.UnauthorizedAccessException: Access to the path '/monitor/swtpm' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at LogService.Lib.Reader.LogEntryReader.GetLastEntriesAsync(String relativeFileName, Nullable`1 maxNumberOfEntries, String filterText) in /app/LogService.Lib/Reader/LogEntryReader.cs:line 53
   at LogService.WebApi.Controllers.LogEntriesController.Get(String filename, Nullable`1 maxNumberOfEntries, String filterText) in /app/LogService.WebApi/Controllers/LogEntriesController.cs:line 48
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Obviously, the service cannot provide log lines from this, but I would expect a more graceful failure & response.

**Comment by aaronwhittier** [comment]
That's reasonable, I'll check it out now.
